version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: honeypot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: honeypot_logs
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: honeypot
      MYSQL_PASSWORD: honeypot_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
